version: '3.8'

services:
  lms_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "50051:50051"
    container_name: lms_server

  lms_client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - lms_server
    container_name: lms_client
    stdin_open: true
    tty: true
